title: Bradley Weiss # your name (or website title) here
logo: "/images/Profilepic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  2+ Years experience in Geographic information Systems. Proficiency in ArcMap and QGIS. Enrolled as an undergraduate student at University of Maryland Baltimore County working towards B.S. in Geography and Environmental Science and a GIS certificate.  
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
